---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: example-awx
  namespace: example-awx
spec:
  deployment_type: awx
  tower_ingress_type: ingress
  tower_web_resource_requirements:
    requests:
      cpu: 500m
      memory: 128M
  tower_task_resource_requirements:
    requests:
      cpu: 500m
      memory: 128M
