---

name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-18.04
    name: Push tagged image to Quay
    steps:
      - uses: actions/checkout@v2

      - name: Install Operator-SDK
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          wget -O $GITHUB_WORKSPACE/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.19.4/operator-sdk-v0.19.4-x86_64-linux-gnu
          chmod +x $GITHUB_WORKSPACE/bin/operator-sdk
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Build Image
        run: |
          operator-sdk build awx-operator:${{ github.event.release.tag_name }}

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: awx-operator
          tags: ${{ github.event.release.tag_name }}
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
